sudo: required

services:
  - docker

env:
  matrix:
    - CI_ROS_DISTRO="galactic"

install:
  - docker build -t phidgets_drivers_$CI_ROS_DISTRO -f Dockerfile-$CI_ROS_DISTRO .

script:
  - docker run phidgets_drivers_$CI_ROS_DISTRO /bin/bash -c "source install/setup.bash && colcon test && colcon test-result"
